# HTTP request arriving at port 3000 (externally)
# Docker maps this to container port 3000
server {
    listen 3000;
    server_name docker-alpine.lucami.org;
}
# HTTPS server running INSIDE the container on port 443
server {
    listen 443 ssl 
    http2 on;
    server_name docker-alpine.lucami.org;

    # Redirect plain HTTP that accidentally hits the HTTPS port
    if ($ssl_protocol = "") {
        return 301 https://$host:3000$request_uri;
    }

    ssl_certificate     /certs/docker-alpine.lucami.org/cert.pem;
    ssl_certificate_key /certs/docker-alpine.lucami.org/privkey.pem;
    ssl_trusted_certificate /certs/docker-alpine.lucami.org/chain.pem;


    ssl_protocols TLSv1.2 TLSv1.3;

    # Path where Vite build artifacts are served
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback for Vite
    location / {
        try_files $uri /index.html;
    }
}
